### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Dens26** [MultipedRobotics/pyservos#1]
Hello,

Great Job. I need help for connecting the Raspberry to the servomotors

Is it possible to drive several ax12 and xl320 with the same code ?

Is it possible to have the plan of the connection of Raspberry to the servomotors AX-12 and XL-320.

I shall like connecting them with a 74ls241

**Comment by walchko** [comment]
Sorry for the late reply, I have been really busy.

I have not tried to drive both ax12 and xl320 servos from the same code. They have different versions of the protocol. I would have one serial port talk to the ax12 and another serial port talk to the xl320. Since the raspberry pi only has one serial port, you would probably have use a usb-to-serial adaptor.
